

import image from '../imagesmall2/housekeeping.jpg'
import image1 from '../imageforday/cook4.jpg'
import image2 from '../imagesmall2/driver.jpg'
import image3 from '../imagesmall2/babysitter3.jpg'
import image4 from '../imagesmall2/images.jpg'
const data = {

    productData: [
        {
            id:1,
            name:"serice",
            img: image,
            service:"Home Maid",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:2,
            name:"serice",
            img: image,
            service:"Home Maid",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },

        {
            id:3,
            name:"serice",
            img: image,
            service:"Home Maid",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:4,
            name:"kcuh bhi",
            img: image,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:5,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        }, {
            id:6,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        }, {
            id:7,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        }, {
            id:8,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        }, 
        {
            id:9,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:10,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:11,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:12,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:13,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:14,
            name:"kcuh bhi",
            img: image1,
            service:"Cleaning",
            price: 600,
            catagory:"all service",
            imformation:"Home Maid can do all home work include home serice",
            imformations:"all in one catagory",
        },
        {
            id:15,
            name:"omkar service",
            img: image2,
            service:"Driver",
            price: 800,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"For day only",
        },
        {
            id:16,
            name:"akshay serives",
            img: image2,
            service:"Cleaning",
            price: 600,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"all in one catagory",
        },
        {
            id:17,
            name:"kcuh bhi",
            img: image2,
            service:"Driver",
            price: 600,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"all in one catagory",
        },
        {
            id:18,
            name:"kcuh bhi",
            img: image2,
            service:"Driver",
            price: 600,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"all in one catagory",
        },
        {
            id:19,
            name:"kcuh bhi",
            img: image2,
            service:"Driver",
            price: 600,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"all in one catagory",
        },
          {
            id:20,
            name:"kcuh bhi",
            img: image2,
            service:"Driver",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"all in one catagory",
        },
        {
            id:21,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:22,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:23,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional Babysitting service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:24,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
          {
            id:25,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:26,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:27,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:28,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional Babysitting service by RazeJobfinder",
            imformations:"Good babysitters",
        },
        {
            id:29,
            name:"laxmi Babysitting service",
            img: image3,
            service:"Babysitter",
            price: 900,
            catagory:"Driving for day",
            imformation:"professional driving service by RazeJobfinder",
            imformations:"Good babysitters",
        },
          {
            id:30,
            name:"lack Babysitting service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
        {
            id:31,
            name:"life Painter service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
        {
            id:32,
            name:"leef Painter service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
        {
            id:33,
            name:"veek Painter service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
        {
            id:34,
            name:"lacky Painter service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
        {
            id:35,
            name:"vicky Painter service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },
          {
            id:36,
            name:"laxmi Babysitting service",
            img: image4,
            service:"Painter",
            price: 900,
            catagory:"Painter for day",
            imformation:"professional Painter service by RazeJobfinder",
            imformations:"Good Painter",
        },

    ],

};


export  default data;